### ISSUE TITLE
Block until a connection is available

### ISSUE THREAD

**Issue by BowlBird** [bjesus/wttrbar#14]
Hello!

I just today found this repo and I'm loving it so far. I have one small gripe however. I'm on a laptop, so as a battery saving feature, wifi gets shut off once the lid closes. This causes problems though as wttrbar tries to get data back before a connection is established once I open the laptop lid. 

I believe the best solution for this is to block the main thread until a connection is established, so that the get call can finish successfully.

For now, I have 
```json
"custom/weather": {
        "format": "{}° ",
        "tooltip": true,
        "interval": 3600,
        "exec": "exit=101; while [ $exit = 101 ]; do wttrbar --main-indicator temp_F --fahrenheit; exit=$(echo $?); sleep 1; done",
        "return-type": "json"
    },
```
in my waybar config, which works, but it's inefficient.

Thanks!

**Comment by bjesus** [comment]
should be fixed now following your PR, thanks again!
