### ISSUE TITLE
Custom indicator implementation

### ISSUE THREAD

**Issue by nut-3** [bjesus/wttrbar#20]
Hello and thank you for the wttrbar )
It almost fully suit my needs, but I'd like to have an option to customize `text` output (having `tamp_c` and `FeelsLikeC` together for example). So I made a fork and did some changes.
First one is `clap` integration as I think it is simpler to extend parameters with it - https://github.com/nut-3/wttrbar/commit/5408fdcc645a685135285826d021a8d8d7b60e80
Second one is adding `--custom-indicator`  - https://github.com/nut-3/wttrbar/commit/e0eb2956eb7d3e2a0eb9a9ae56c8cd58db86b221
If you consider that changes can be useful, I can make a PR, or feel free to just copy some parts.

**Comment by teto** [comment]
Plain user here, I second the change to clap if it gives us an `--help` flag. Was going to open a ticket about this very issue.

**Comment by bjesus** [comment]
that's a nice idea, and can probably come instead of `--vertical-view`, because it would be easy to just do `{ICON}\n{FeelsLikeF}`, right?

**Comment by bjesus** [comment]
should be working now, thakn you @nut-3 !
