### ISSUE TITLE
Wind in MPH would be a nice option

### ISSUE THREAD

**Issue by nixfu** [bjesus/wttrbar#21]
Yes, I know there are only a few of countries in the world that do not use the metric system, but there are lots of us in those countries.

You would probably be better off dropping the --fahrenheit option, and just adding an option to enable US units with the "?units=u" option to wttr.in instead.

OR maybe a way for the user to pass CUSTOM OPTIONS that will be added to the request URL.

**Comment by nut-3** [comment]
While the maintainer is absent, you can take a look at my fork, which has this changes - https://github.com/nut-3/wttrbar/tree/develop
Please, read carefully through readme, as configuration and parameters have changed a lot.

**Comment by bjesus** [comment]
@nut-3 please feel free to submit a PR with the relevant changes and I'll be happy to merge it

**Comment by nut-3** [comment]
> @nut-3 please feel free to submit a PR with the relevant changes and I'll be happy to merge it

@bjesus well, I've submitted #22 already. But then I continued to hack the code to suit my needs (and learn rust) and it turned into pretty serious refactoring with changing option names, adding tokio crate and stuff. I'll submit it, but it breaks backward-compatibility, so don't sure if it is a good idea to merge everything at once.
Created #23.

**Comment by dianaw353** [comment]
I have added the option to change the wind measurement in PR #48. This adds a flag --mph that would enable/disable the option

**Comment by bjesus** [comment]
this is now released as part of wttrbar 0.10.0. thanks @dianaw353 !
