### ISSUE TITLE
[Request] Change Mist Icon to not be a square

### ISSUE THREAD

**Issue by BowlBird** [bjesus/wttrbar#25]
I'm not sure what icons are available at all, however every icon other than mist has a more rounded appearance which makes 'mist' stand out as it is nearly a white square. Is there any way this could be changed to a more fitting icon?

**Comment by bjesus** [comment]
I noticed this too. Note that wttrbar just uses the fog emoji, but the way it looks really depends on your font. https://emojipedia.org/fog shows that indeed most fonts draw it as a square icon. I'm happy to consider changing it something else but not sure which one is more fitting? there's a "foggy" icon but it's also a square usually.

**Comment by daxisunder** [comment]
All the icons shown on the Waybar are square, change them to those in the hourly forecast.

**Comment by bjesus** [comment]
The same icons are used for the main indicator and for the tooltip. If you're seeing something else, please provide a screenshot as something seems to be broken with your setup.

**Comment by BowlBird** [comment]
I'm going to close this as I'm not sure there is a great solution to this without repeating icons. I wish there was a more rounded mist but without something like a custom icon I don't know that it's this repo's responsibility.

**Comment by amanhex** [comment]
![image](https://github.com/user-attachments/assets/3dec18df-2530-45a3-8a83-e3491879de66)

Yea, mist emoji does feels off than the rest used in this module.
