### ISSUE TITLE
24h formatting of sunset and sunrise times

### ISSUE THREAD

**Issue by fhmbrg** [bjesus/wttrbar#3]
I'm not using parameter `--ampm` but the shown time is in am/pm format. How to define a 24H time output?

**Comment by bjesus** [comment]
Your output is not really in am/pm notation, hence stuff like `21 🌦️ 1° Patchy rain possible, Rain 85%, Overcast 83%`. Note it says 21 and not 9pm. For sunrise and sunset it has always been in am/pm because this is how it comes from wttr.in - I'll keep this issue open until it's fixed.

**Comment by fhmbrg** [comment]
Thanks, glad to read. The "problem" is purely cosmetically.
