### ISSUE TITLE
[Feature] Send notification if there is errors

### ISSUE THREAD

**Issue by dianaw353** [bjesus/wttrbar#30]
I am curious if accept adding notifications to wttrbar as there are times that  wttr.in is down and the user dose not know that so it would be nice to know if the service is down when it tries to receive the data from wttr.in. Also It would be nice to receive a notification if the location the user types is unknown so if it dose it also displays a notification.  I have a current prototype on my machine currently and from what i can tell as the service is down is that it works...

Reason:
As most people are not tech savy to run wttrbar via the command and run it just with waybar it would be nice to show the info via a notification why the module isnt showing/populating with info.

**Comment by alekgr** [comment]
I totally agree, right now https://wttr.in/ is down, it took me a minute  to figure out the site is down
