### ISSUE TITLE
Assign Different Characters?

### ISSUE THREAD

**Issue by 5p4r74cu5** [bjesus/wttrbar#31]
Hey there, thanks for working on this :-) I'm just setting up waybar on Hyprland and it looks great.

However I'm wondering if there is a config hidden somewhere where I can change the default characters used for the different weather states (sun emoji, rain emoji, etc) and replace with custom ones that match the theme of my waybar?

**Comment by bjesus** [comment]
There isn't really anything like that, but I'm assuming you can configure Waybar to use whichever emoji font you want

**Comment by 5p4r74cu5** [comment]
Okay, no worries :-)

Yes you can change the font, but I wanted to change the emogis to icons/

**Comment by bjesus** [comment]
I don't think that would be technically possible, as Waybar doesn't support getting images in the tooltip content AFAIK.

**Comment by 5p4r74cu5** [comment]
I don't think they support images at all, although I may be mistaken, I meant non standard icons from Font Awesome for example, not technically images.
