### ISSUE TITLE
Detect location

### ISSUE THREAD

**Issue by h-2** [bjesus/wttrbar#32]
It would be great to have automatic location detection! This could be done for free via http://ifconfig.co/ or a similar service.

**Comment by bjesus** [comment]
The location is done automatically. You can choose to override it with `--location` if you want.

**Comment by h-2** [comment]
Hm, but it auto-detects someplace completely different from where I live. All other location services (like the aforementioned ifconfig.co or google maps) work correctly.

**Comment by bjesus** [comment]
Wttrbar doesn't do any location detection. It's wttr.in that does it. If it works with wttr.in (you can check in the browser), it should work with Wttrbar. Location detection is done based on IP, so unless you're using a VPN it should be good enough. If it isn't, you can override it with `--location`.

**Comment by h-2** [comment]
Yeah, the detection of wttr.in is completely off. Every other service gets it right 🤔

**Comment by bjesus** [comment]
sorry, sounds like this should be fixed at https://github.com/chubin/wttr.in/ then, not here

**Comment by alexander-belikov** [comment]
in case wttr.in detects my location correctly, but wttrbar does not...
