### ISSUE TITLE
wttrbar causes sway to fail to load

### ISSUE THREAD

**Issue by elilassman** [bjesus/wttrbar#44]
I've just switched from the original wttr script to wttrbar.  Since switching sway fails to fully load on startup.  When starting up I see just  a grey screen with a cursor until I manually open a terminal window.  Then everything loads correctly, including wttrbar.

I've isolated the issue to adding the --location variable, as when I remove it from my waybar config waybar and sway (Chrome windows, sway background, etc) load as expected.

"exec": "~/.config/waybar/Scripts/wttrbar", loads with no issues
"exec": "~/.config/waybar/Scripts/wttrbar --location London", causes sway to hang

A colleague built a separate script that sets the --location variable outside of the config file and that solves the issue, but it feels sub-optimal to have to create a separate script.

**Comment by bjesus** [comment]
if calling a script that calls `wttrbar --location London` works fine, it sounds like an issue with Waybar... what does the script look like?

**Comment by bjesus** [comment]
also what version of sway/waybar/wttrbar are you running?

**Comment by elilassman** [comment]
Running the script works as expected.  I've also installed waybar on a second laptop using the  '--location London' variable and that does not stop sway from starting.

sway version:  1.9-rc.1
waybar: v0.9.24
wttrbar: 0.9.4 

I've checked my config and everything looks substantially similar, so I'll try updating everything, then add in the location variable and see if the issue persists.

**Comment by elilassman** [comment]
This has resolved itself; without changing the config, so not sure what was initially causing the issue.
