### ISSUE TITLE
Way to not show an icon?

### ISSUE THREAD

**Issue by tristengrant** [bjesus/wttrbar#45]
Is there a way to not show the weather icon?

**Comment by bjesus** [comment]
in the bar or in the tooltip? for the bar you can use `--custom-indicator`. for the tooltip, no such way currently

**Comment by tmpm697** [comment]
> in the bar or in the tooltip? for the bar you can use `--custom-indicator`. for the tooltip, no such way currently

i tried `    // "exec": "wttrbar --date-format '%m/%d' --location Paris --hide-conditions --custom-indicator=\"{temp_C}({FeelslikeC})\"",` --> still shows icons next to temp like `<icon> 24*`

**Comment by tristengrant** [comment]
Using **exec": ""wttrbar --location <your-location> --custom-indicator {temp_C}"** worked for me.

**Comment by tmpm697** [comment]
> Using **"exec": "wttrbar --location --custom-indicator {temp_C}"** worked for me.

not work for me, there's still icon before temp: `<sun_icon> 27*`

**Comment by bjesus** [comment]
it works fine here. what version are you running?

**Comment by tmpm697** [comment]
> it works fine here. what version are you running?

how to check version? i probably using this version 0.6.0: https://search.nixos.org/packages?query=wttrbar

**Comment by bjesus** [comment]
` --custom-indicator` support was added at 0.7.0. I'm not maintaining the nix package so can't really help here.
