### ISSUE TITLE
wind direction is not shown

### ISSUE THREAD

**Issue by r1kk** [bjesus/wttrbar#5]
I miss this feature. It is shown on wttr.in.

**Comment by bjesus** [comment]
hey! how and where do you wish it was displayed? happy to look into it

**Comment by bjesus** [comment]
closing for no response.

**Comment by dianaw353** [comment]
hay i would like to see this to be before the wind speed number

**Comment by r1kk** [comment]
I agree with dianaw353.
also a simplified arrow emoji would be nice before the winddir same way as for the weather description.
if wttr.in gives two direction at once like "SSW" then two arrow emoji like "up,upright".
