### ISSUE TITLE
wind direction emoticon

### ISSUE THREAD

**Issue by musicfunfan** [bjesus/wttrbar#63]
So before i found this project i was using to display the weather this command. 

``curl wttr.in/location?format=2 -s``

With this command i was getting this out put. 

``☀️   🌡️+31°C 🌬️↙14km/h``

I would like to keep this out put and also keep the tool-tip that your module provide. Can i do this ?

I can not find how to display the wind direction with this arrow who points like the compass. 

All the other things i manage to replicate.

**Comment by bjesus** [comment]
I don't think we support the wind direction currently in wttrbar. I guess you can always just patch the `test` field like this:

```
wttrbar | jq ".text = \"$(curl 'wttr.in/location?format=2' -s)\""
```

**Comment by musicfunfan** [comment]
Ok understood.
