### ISSUE TITLE
how to add it?

### ISSUE THREAD

**Issue by adocampo** [bjesus/wttrbar#65]
I'm new to waybar, so I don't know how to add new modules. 
I see I  have a directory `~/.config/waybar` with several files (config.ctl, config.jsonc, style.css and theme.css) and a subdirectory "modules" with a bunch of jsonc files (clock.jsonc, battery.jsonc, etc)

I guess wttrbar should be placed here in `modules/wttrbar.jsonc`, with this content
```
"custom/weather": {
    "format": "{}°",
    "tooltip": true,
    "interval": 3600,
    "exec": "wttrbar --lang es  --date-format "%d/%m" --location "Nou Barris" --hide-conditions",
    "return-type": "json"
},
```

but I do not know how to add it to my waybar.

**Comment by bjesus** [comment]
this really isn't a wttrbar issue. see the waybar documentation: https://github.com/Alexays/Waybar/wiki/Configuration you need to specify where to place the module using modules-{left/center/right}
