### ISSUE TITLE
Print out locaiton via --custom-indicator

### ISSUE THREAD

**Issue by jcbevns** [bjesus/wttrbar#67]
is it possible already to print out `{location}` like `{icon}`?

**Comment by bjesus** [comment]
Nice idea, should be possible now with wttrbar 0.11.0

**Comment by jcbevns** [comment]
You're fast :) I was gonna take a look at the Rust code shortly as a nice first Rust dive.. But now its done!  Thank you.

Can we also get it into [nixpkgs unstable](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/wt/wttrbar/package.nix#L11)? Or a release, or should I just build from source? 

Can help with putting release-please on the repo to make it easier if you want (release)

**Comment by bjesus** [comment]
Haha, the one time I'm not answering with "feel free to send a PR" 😅

I'm actually not the maintainer for the nixpkg for wttrbar. I do get automatic notifications for other nixpkgs that I maintain - usually the nix bots take care of creating a PR after a release is created on Github. If you can help me with updating the nixpkg that would be great!

A release was already created: https://github.com/bjesus/wttrbar/releases/tag/0.11.0 and it has binaries if you just want to use that.

**Comment by jcbevns** [comment]
How do I use it? `.local/bin/wttrbar --custom-indicator '{location} {ICON} {temp_C}'"` doesn't seem to be working for me in my `/waybar/config.jsonc` and I don't see it mentioned in the `--help`

**Comment by bjesus** [comment]
You can use keys under the `nearest_area` section, like `{areaName}`, `{county}` or `{region}`. I'll update the README and the `--help` output
