### ISSUE TITLE
nitpick: `--custom-indicator` always shows the degree symbol `°` last

### ISSUE THREAD

**Issue by odomingao** [bjesus/wttrbar#72]
very small nitpick, but `--custom-indicator='{ICON}  {temp_C} C'` results in the "C" being displayed before the `°`

**Comment by bjesus** [comment]
I'm a little confused - when using `--custom-indicator='{ICON}  {temp_C} C'` there's no `°` at all:
```
❯ wttrbar --custom-indicator='{ICON}  {temp_C} C' | jq .text
"🌧️  7 C"
```

If you want to have the ° symbol you should include it in the value, like this:
```
❯ wttrbar --custom-indicator='{ICON}  {temp_C}°C' | jq .text
"🌧️  7°C"
```

**Comment by odomingao** [comment]
You are right... I had added the degree field to the `format` field and forgot about it. Sorry for the dumb issue.
