### ISSUE TITLE
https://github.com/bjesus/wttrbar/blob/main/README.md

### ISSUE THREAD

**Issue by WgpArch** [bjesus/wttrbar#73]
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the webpage mentioned above.

**Comment by bjesus** [comment]
wttr.in had an issue with their certificate, this has nothing to do with wttrbar.
